on: push
name: Test and Build
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
       - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage

      - name: Build Android Appbundle
        run: flutter build appbundle

      # - name: Build iOS
      #   run: flutter build ios --release --no-codesign
    # - name: Create a Release APK
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "build/app/outputs/apk/debug/*.apk"
    #     token: ${{ secrets.TOKEN }}